Method,Name,Error,Occurrences
GET,/Categorias,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",774
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 7'),710
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 6'),271
GET,/Productos,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",526
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 3'),198
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 8'),267
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 2'),192
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 3'),213
GET,/Categorias,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",923
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 4'),211
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 7'),185
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 1'),695
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 4'),192
GET,/Pedidos/5925,HTTPError('500 Server Error: Internal Server Error for url: /Pedidos/5925'),2583
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 12'),182
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 11'),660
GET,/Mesas,RemoteDisconnected('Remote end closed connection without response'),172
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 9'),194
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 3'),693
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 7'),214
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 9'),276
GET,/Productos,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",403
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 9'),180
GET,/Pedidos/5925,RemoteDisconnected('Remote end closed connection without response'),549
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 12'),187
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 2'),304
GET,/Mesas,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",236
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 11'),197
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 3'),210
GET,/Pedidos/5925,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",549
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 9'),198
GET,/Categorias,HTTPError('500 Server Error: Internal Server Error for url: /Categorias'),3378
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 7'),293
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 1'),219
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 10'),293
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 13'),190
GET,/Mesas,HTTPError('500 Server Error: Internal Server Error for url: /Mesas'),831
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 8'),201
GET,/Pedidos/5925,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",671
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 1'),175
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 12'),179
GET,/Categorias,RemoteDisconnected('Remote end closed connection without response'),726
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 2'),200
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 13'),197
GET,/Mesas,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",192
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 5'),684
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 8'),715
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 5'),183
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 5'),183
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 1'),213
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 12'),188
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 9'),204
GET,/Productos,"ConnectionAbortedError(10053, 'Se ha anulado una conexión establecida por el software en su equipo host', None, 10053, None)",1
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 10'),698
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 1'),290
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 2'),664
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 8'),194
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 4'),299
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 11'),182
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 2'),203
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 7'),213
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 3'),292
GET,/Productos,HTTPError('500 Server Error: Internal Server Error for url: /Productos'),3283
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 5'),270
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 13'),208
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 6'),688
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 9'),743
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 4'),697
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 11'),183
GET,/Productos,RemoteDisconnected('Remote end closed connection without response'),1558
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 11'),187
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 13'),190
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 4'),176
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 2'),177
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 5'),186
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 8'),186
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 1'),236
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 5'),210
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 8'),182
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 4'),182
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 11'),283
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 3'),198
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 7'),200
