Method,Name,Error,Occurrences
GET,/Categorias,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",136
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 7'),424
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 6'),609
GET,/Productos,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",79
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 3'),448
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 8'),610
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 2'),419
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 3'),422
GET,/Categorias,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",350
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 4'),438
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 7'),483
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 1'),415
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 4'),435
GET,/Pedidos/5925,HTTPError('500 Server Error: Internal Server Error for url: /Pedidos/5925'),3
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 12'),432
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 11'),410
GET,/Mesas,RemoteDisconnected('Remote end closed connection without response'),642
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 9'),411
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 3'),430
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 7'),453
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 9'),631
GET,/Productos,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",36
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 9'),415
GET,/Pedidos/5925,RemoteDisconnected('Remote end closed connection without response'),1885
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 12'),439
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 2'),685
GET,/Mesas,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",89
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 11'),415
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 3'),435
GET,/Pedidos/5925,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",115
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 9'),432
GET,/Categorias,HTTPError('500 Server Error: Internal Server Error for url: /Categorias'),3
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 7'),599
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 1'),398
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 10'),627
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 13'),394
GET,/Mesas,HTTPError('500 Server Error: Internal Server Error for url: /Mesas'),2
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 8'),441
GET,/Pedidos/5925,"ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x....>, 'Connection to 192.168.100.15 timed out. (connect timeout=None)')",270
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 1'),397
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 12'),449
GET,/Categorias,RemoteDisconnected('Remote end closed connection without response'),2611
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 2'),420
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 13'),436
GET,/Mesas,"ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None)",37
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 5'),431
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 8'),409
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 5'),460
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 5'),469
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 1'),415
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 12'),429
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 9'),407
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 10'),403
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 1'),585
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 2'),425
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 8'),463
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 4'),594
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 11'),402
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 2'),434
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 7'),466
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 3'),612
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 5'),603
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 13'),432
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 6'),454
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 9'),423
PUT,Abrir Mesa,CatchResponseError('Fallo al abrir mesa 4'),406
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 11'),388
GET,/Productos,RemoteDisconnected('Remote end closed connection without response'),4986
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 11'),459
POST,Agregar Item,CatchResponseError('Fallo al agregar item 1 en mesa 13'),416
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 4'),430
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 2'),432
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 5'),441
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 8'),375
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 1'),400
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 5'),504
POST,Agregar Item,CatchResponseError('Fallo al agregar item 3 en mesa 8'),432
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 4'),448
PUT,Cerrar Mesa,CatchResponseError('Fallo al cerrar mesa 11'),593
POST,Agregar Item,CatchResponseError('Fallo al agregar item 4 en mesa 3'),437
POST,Agregar Item,CatchResponseError('Fallo al agregar item 2 en mesa 7'),421
